[package]
name = "godotqr"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
godot = { git = "https://github.com/godot-rust/gdext", branch = "master" }
qrcode = { version = "0.11", default-features = false }

[profile.release]
strip = true # Remove debug symbols